<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240224124420 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE experimentation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, num_exp VARCHAR(25) NOT NULL, type_exp VARCHAR(50) NOT NULL, site_essai VARCHAR(50) NOT NULL, syst_essai VARCHAR(25) NOT NULL, lot_cell VARCHAR(25) NOT NULL, passage VARCHAR(25) NOT NULL, stress VARCHAR(50) NOT NULL, temps_traitement VARCHAR(25) NOT NULL, gene VARCHAR(25) NOT NULL, prot_analyse VARCHAR(255) DEFAULT NULL, gene_corr VARCHAR(50) DEFAULT NULL, projet VARCHAR(50) NOT NULL, nom_item VARCHAR(25) DEFAULT NULL, nom_comm VARCHAR(50) DEFAULT NULL, ref_produit VARCHAR(25) DEFAULT NULL, pourcentage_produit VARCHAR(25) DEFAULT NULL, genre VARCHAR(25) DEFAULT NULL, espece VARCHAR(25) DEFAULT NULL, fold_change VARCHAR(25) DEFAULT NULL, augm_dim VARCHAR(25) DEFAULT NULL, notation VARCHAR(25) DEFAULT NULL, prot_corr VARCHAR(255) DEFAULT NULL, source_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF9EE405953C1C61 ON experimentation (source_id)');
        $this->addSql('ALTER TABLE experimentation ADD CONSTRAINT FK_CF9EE405953C1C61 FOREIGN KEY (source_id) REFERENCES data_source (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE experimentation DROP CONSTRAINT FK_CF9EE405953C1C61');
        $this->addSql('DROP TABLE experimentation');
    }
}
